# Theme
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-114243378-7
# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
# Theme Settings
logo: /assets/02-mirror-large.jpg
